apiVersion: apps/v1
kind: Deployment
metadata:
  name: openldap
  labels:
    app.kubernetes.io/name: openldap
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.teams: Alerts #Teams Channel
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: openldap
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: openldap
    spec:
      containers:
        - name: openldap
          image: docker.io/bitnami/openldap:latest
          imagePullPolicy: "Always"
          env:
            - name: LDAP_ADMIN_USERNAME
              value: "admin"
            - name: LDAP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: adminpassword
                  name: openldap
            - name: LDAP_USERS
              valueFrom:
                secretKeyRef:
                  key: users
                  name: openldap
            - name: LDAP_PASSWORDS
              valueFrom:
                secretKeyRef:
                  key: passwords
                  name: openldap
          ports:
            - name: tcp-ldap
              containerPort: 1389

---

apiVersion: v1
kind: Service
metadata:
  name: openldap
  labels:
    app.kubernetes.io/name: openldap
spec:
  type: NodePort
  ports:
    - name: tcp-ldap
      port: 1389
      targetPort: tcp-ldap
      nodePort: 30389
  selector:
    app.kubernetes.io/name: openldap

---
apiVersion: v1
kind: Secret
metadata:
  name: openldap
type: Opaque
data:
  username: dXNlcm5hbWU=  # base64 encoded value of 'username'
  password: cGFzc3dvcmQ=  # base64 encoded value of 'password'
  adminpassword: dXNlcm5hbWU
