apiVersion: v1  
kind: Secret
metadata:   
  name: argocd-notifications-secret
stringData:
  channel-teams-url: "https://prod-18.westus.logic.azure.com:443/workflows/18eeaf2299244dda878fca596f1e368e/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=3e8eG_SWD3zVtME9myruhHwF2N86n9NxDNNitV4u3Ec"
type: Opaque
